services:
  neo4j-service:
    build: ./neo4j-service
    image: neo4j-service
    ports:
      - 4000:4000
    volumes:
      - ./neo4j-service:/app
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./neo4j-service/package.json
        - action: rebuild
          path: ./neo4j-service/package-lock.json
        - action: sync+restart
          target: /app
          path: ./neo4j-service
  textMRI-service: 
    depends_on: 
      - neo4j-service
    build:
      context: ./textMRI-service
      target: development
    image: textmri-service
    volumes:
      - ./textMRI-service:/app
    ports: 
      - 4001:4001
    networks:
      - app-network
    develop:
      watch:
        - action: rebuild
          path: ./textMRI-service/package.json
        - action: rebuild
          path: ./textMRI-service/package-lock.json
        - action: sync+restart
          target: /app
          path: ./textMRI-service

networks:
  app-network: