type Text {
  name: String!
  id: Int!
  isDocument: Document @relationship(type: "IS", direction: OUT)
  propositionsDecision: Decision @relationship(type: "PROPOSITIONS", direction: OUT)
  mustHaveKnowledge: Knowledge @relationship(type: "MUST_HAVE", direction: OUT)
  referencesReference: Reference @relationship(type: "REFERENCES", direction: OUT)
  mustContainEnvironment: Environment @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainPurpose: Purpose @relationship(type: "MUST_CONTAIN", direction: OUT)
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  imageMayContain: Image @relationship(type: "MAY_CONTAIN", direction: IN)
  audiotranscriptMayContain: AudioTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
  imagetranscriptMayContain: ImageTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
  listenerAudienceOf: Listener @relationship(type: "AUDIENCE_OF", direction: IN)
  documentownerOwns: DocumentOwner @relationship(type: "OWNS", direction: IN)
}

type TextTranscript {
  transcript_text: String!
  transcript_name: String!
  mustContainText: Text @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainActor: Actor @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainTurn: Turn @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainTopic: Topic @relationship(type: "MUST_CONTAIN", direction: OUT)
  videotranscriptMayContain: VideoTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
}

type Actor {
  name: String!
  id: Int!
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  turnDifferentiatedBy: Turn @relationship(type: "DIFFERENTIATED_BY", direction: IN)
  audiotranscriptMayContain: AudioTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
  imagetranscriptMayContain: ImageTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
}

type Turn {
  turn_number: Int!
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  differentiatedByActor: Actor @relationship(type: "DIFFERENTIATED_BY", direction: OUT)
  differentiatedByTopic: Topic @relationship(type: "DIFFERENTIATED_BY", direction: OUT)
}

type Audio {
  file: String!
  size: Int!
  ifTranscribedAudiotranscript: AudioTranscript @relationship(type: "IF_TRANSCRIBED", direction: OUT)
  videoSegmentedBySound: Video @relationship(type: "SEGMENTED_BY_SOUND", direction: IN)
}

type Video {
  title: String!
  length: Int!
  link: String!
  frame_rate: Int!
  segmentedBySoundAudio: Audio @relationship(type: "SEGMENTED_BY_SOUND", direction: OUT)
  segmentedByImageFrame: Frame @relationship(type: "SEGMENTED_BY_IMAGE", direction: OUT)
  containsTranscriptVideotranscript: VideoTranscript @relationship(type: "CONTAINS_TRANSCRIPT", direction: OUT)
}

type Frame {
  Frame_number: Int!
  videoSegmentedByImage: Video @relationship(type: "SEGMENTED_BY_IMAGE", direction: IN)
  mustContainImage: Image @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Reference {
  title: String!
  author: String!
  source: String!
  type: String!
  textReferences: Text @relationship(type: "REFERENCES", direction: IN)
}

type Topic {
  name: String!
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  turnDifferentiatedBy: Turn @relationship(type: "DIFFERENTIATED_BY", direction: IN)
}

type Image {
  coordinates: Int!
  pixels_x: Int!
  pixels: Int!
  pixels_y: Int!
  frameMustContain: Frame @relationship(type: "MUST_CONTAIN", direction: IN)
  mayContainText: Text @relationship(type: "MAY_CONTAIN", direction: OUT)
  ifTranscribedImagetranscript: ImageTranscript @relationship(type: "IF_TRANSCRIBED", direction: OUT)
}

type AudioTranscript {
  transcript: String!
  word_count: Int!
  sentence_count: Int!
  character_count: Int!
  audioIfTranscribed: Audio @relationship(type: "IF_TRANSCRIBED", direction: IN)
  mayContainText: Text @relationship(type: "MAY_CONTAIN", direction: OUT)
  mustContainTimestamp: Timestamp @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainVolume: Volume @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayContainActor: Actor @relationship(type: "MAY_CONTAIN", direction: OUT)
  videotranscriptMustContain: VideoTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Timestamp {
  time: String!
  audiotranscriptMustContain: AudioTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Volume {
  volume: Int!
  audiotranscriptMustContain: AudioTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type ImageTranscript {
  transcript: String!
  imageIfTranscribed: Image @relationship(type: "IF_TRANSCRIBED", direction: IN)
  mustContainColor: Color @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayContainEntity: Entity @relationship(type: "MAY_CONTAIN", direction: OUT)
  mayContainActor: Actor @relationship(type: "MAY_CONTAIN", direction: OUT)
  mayContainText: Text @relationship(type: "MAY_CONTAIN", direction: OUT)
  videotranscriptMustContain: VideoTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Color {
  color_code: String!
  imagetranscriptMustContain: ImageTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Entity {
  id: Int!
  imagetranscriptMayContain: ImageTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
}

type VideoTranscript {
  transcript: String!
  videoContainsTranscript: Video @relationship(type: "CONTAINS_TRANSCRIPT", direction: IN)
  mustContainImagetranscript: ImageTranscript @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainAudiotranscript: AudioTranscript @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayContainTexttranscript: TextTranscript @relationship(type: "MAY_CONTAIN", direction: OUT)
}

type Document {
  turn: Int!
  speaker: String!
  content: String!
  role: String!
  textIs: Text @relationship(type: "IS", direction: IN)
  mustContainEthos: Ethos @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainPathos: Pathos @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainLogos: Logos @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainStyle: Style @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainSoundstylistic: SoundStylistic @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainEuphony: Euphony @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainCohesion: Cohesion @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainHumor: Humor @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainClarity: Clarity @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainSection: Section @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainTopic: Topic @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Paragraph {
  paragraph_number: Int!
  claims: [String!]
  sentence_count: Int!
  claim_count: Int!
  mayContainSentence: Sentence @relationship(type: "MAY_CONTAIN", direction: OUT)
  mustContainCharacter: Character @relationship(type: "MUST_CONTAIN", direction: OUT)
  sectionMustContain: Section @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Sentence {
  claim: String!
  number_of_clauses: Int!
  amount_of_words: Int!
  sentence_index: Int!
  amount_dep_clause: Int!
  amount_indep_clause: Int!
  sentence_structure: [String!]
  paragraphMayContain: Paragraph @relationship(type: "MAY_CONTAIN", direction: IN)
  mustContainIndependentclause: IndependentClause @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayConainDependentclause: DependentClause @relationship(type: "MAY_CONAIN", direction: OUT)
  mayBeSimple: Simple @relationship(type: "MAY_BE", direction: OUT)
  mayBeCompound: Compound @relationship(type: "MAY_BE", direction: OUT)
  mayBeCompoundcomplex: CompoundComplex @relationship(type: "MAY_BE", direction: OUT)
  isTypeDeclarative: Declarative @relationship(type: "IS_TYPE", direction: OUT)
  mayBeInterrogative: Interrogative @relationship(type: "MAY_BE", direction: OUT)
  mayBeImperative: Imperative @relationship(type: "MAY_BE", direction: OUT)
  mayBeExclamatory: Exclamatory @relationship(type: "MAY_BE", direction: OUT)
}

type IndependentClause {
  clause: String!
  word_count: Int!
  clause_index: Int!
  sentenceMustContain: Sentence @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainWord: Word @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayBeClaim: Claim @relationship(type: "MAY_BE", direction: OUT)
  mayBeMetaphor: Metaphor @relationship(type: "MAY_BE", direction: OUT)
  mayBeSimile: Simile @relationship(type: "MAY_BE", direction: OUT)
  mayBeFallacies: Fallacies @relationship(type: "MAY_BE", direction: OUT)
  simpleMustHave: Simple @relationship(type: "MUST_HAVE", direction: IN)
  compoundMustHave: Compound @relationship(type: "MUST_HAVE", direction: IN)
  compoundcomplexMustHave: CompoundComplex @relationship(type: "MUST_HAVE", direction: IN)
}

type Word {
  word_length: Int!
  character_amount: Int!
  Word_index: Int!
  independentclauseMustContain: IndependentClause @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainCharacter: Character @relationship(type: "MUST_CONTAIN", direction: OUT)
  isPartofspeech: PartOfSpeech @relationship(type: "IS", direction: OUT)
  mayBeNamedentity: NamedEntity @relationship(type: "MAY_BE", direction: OUT)
  dependentclauseMustContain: DependentClause @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Character {
  character_index: Int!
  paragraphMustContain: Paragraph @relationship(type: "MUST_CONTAIN", direction: IN)
  wordMustContain: Word @relationship(type: "MUST_CONTAIN", direction: IN)
  mayBePunctuation: Punctuation @relationship(type: "MAY_BE", direction: OUT)
  mustHaveColor: Color @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveWeight: Weight @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveCharactertype: CharacterType @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveCharacterstyle: CharacterStyle @relationship(type: "MUST_HAVE", direction: OUT)
  mayBeAlphabet: Alphabet @relationship(type: "MAY_BE", direction: OUT)
  mayBeNumerics: Numerics @relationship(type: "MAY_BE", direction: OUT)
  mayBeSpecialcharacters: SpecialCharacters @relationship(type: "MAY_BE", direction: OUT)
}

type Punctuation {
  mark: String!
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
  interrogativeMayHave: Interrogative @relationship(type: "MAY_HAVE", direction: IN)
  exclamatoryMayHave: Exclamatory @relationship(type: "MAY_HAVE", direction: IN)
}

type Claim {
  Claim: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type Metaphor {
  Metaphor: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type Simile {
  Simile: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type DependentClause {
  clause: String!
  word_count: Int!
  clause_index: Int!
  sentenceMayConain: Sentence @relationship(type: "MAY_CONAIN", direction: IN)
  mustContainWord: Word @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayBeArgument: Argument @relationship(type: "MAY_BE", direction: OUT)
  compoundcomplexMustHave: CompoundComplex @relationship(type: "MUST_HAVE", direction: IN)
}

type PartOfSpeech {
  word_count: Int!
  wordIs: Word @relationship(type: "IS", direction: IN)
  imperativeMustHave: Imperative @relationship(type: "MUST_HAVE", direction: IN)
}

type NamedEntity {
  id: Int!
  name: String!
  wordMayBe: Word @relationship(type: "MAY_BE", direction: IN)
  externalactorsMayContain: ExternalActors @relationship(type: "MAY_CONTAIN", direction: IN)
}

type Argument {
  Argument: [String!]
  word_count: Int!
  premises: [String!]
  conclustion: [String!]
  consequences: [String!]
  premise_count: Int!
  dependentclauseMayBe: DependentClause @relationship(type: "MAY_BE", direction: IN)
  mustContainPremise: Premise @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainConsequence: Consequence @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Ethos {
  score: [Float!]
  explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Pathos {
  score: [Float!]
  explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Logos {
  score: [Float!]
  explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
  mustHavePremise: Premise @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveConclusion: Conclusion @relationship(type: "MUST_HAVE", direction: OUT)
}

type Style {
  style_score_tensor: [Int!]
  register: Int!
  sound_stylistic: Int!
  euphony_hueristic: Int!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
  containsStylescoretensor: StyleScoreTensor @relationship(type: "CONTAINS", direction: OUT)
}

type SoundStylistic {
  rhyme_score: Float!
  alliteration_score: Float!
  assonance_score: Float!
  consonance_score: Float!
  rhythm_score: Float!
  onomatopoeia: [String!]
  rhyme_explanation: String!
  alliteration_explanation: String!
  assonance_explanation: String!
  consonance_explanation: String!
  rythm_explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Euphony {
  three_syllable_words: [String!]
  three_syllable_count: Int!
  short_vowels_words: [String!]
  stress_pattern_words: [String!]
  short_vowels_count: Int!
  stress_pattern_count: Int!
  count: Int!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Cohesion {
  Relevancy_Score: Float!
  Continuity_Score: Float!
  topic_transition_Score: Float!
  Relevancy_explanation: String!
  continuity_explanation: String!
  topic_transition_explanation: String!
  score: Float!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Humor {
  score: Float!
  explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Clarity {
  score: Float!
  grammar_expl: String!
  readability_score: Float!
  grammar_score: Float!
  readability_expl: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Agents {
  name: String!
  mayBeListener: Listener @relationship(type: "MAY_BE", direction: OUT)
  mayBeDocumentowner: DocumentOwner @relationship(type: "MAY_BE", direction: OUT)
}

type ExternalActors {
  name: String!
  id: Int!
  mayContainNamedentity: NamedEntity @relationship(type: "MAY_CONTAIN", direction: OUT)
  mustHavePsychographics: Psychographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveDemographics: Demographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveMindstate: Mindstate @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveBias: Bias @relationship(type: "MUST_HAVE", direction: OUT)
}

type Fallacies {
  fallacy_type: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type Premise {
  parameters: [String!]
  index: Int!
  word_count: Int!
  argumentMustContain: Argument @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainPremiseparameters: PremiseParameters @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Consequence {
  parameters: [String!]
  index: Int!
  word_count: Int!
  argumentMustContain: Argument @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainConsequenceparameters: ConsequenceParameters @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type PremiseParameters {
  accuracy: Float!
  premiseMustContain: Premise @relationship(type: "MUST_CONTAIN", direction: IN)
}

type ConsequenceParameters {
  Plausibility: Float!
  consequenceMustContain: Consequence @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Section {
  Section_name: String!
  section_number: Int!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainParagraph: Paragraph @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Environment {
  context: String!
  audience: String!
  purpose: String!
  language: String!
  textMustContain: Text @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Purpose {
  purpose: String!
  audience: String!
  textMustContain: Text @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Psychographics {
  personality: String!
  interests: [String!]
  beliefs: [String!]
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
}

type Demographics {
  age: Int!
  gender: String!
  race: String!
  ethnicity: String!
  income: Int!
  location: String!
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
}

type Mindstate {
  emotional_state: String!
  cognitive_state: String!
  confidence: String!
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
}

type Bias {
  bias_type: String!
  category: String!
  cognitive_influence: [String!]
  emotional_influence: [String!]
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
}

type Decision {
  decision: String!
  textPropositions: Text @relationship(type: "PROPOSITIONS", direction: IN)
}

type Premise {
  premise_strength: Float!
  logosMustHave: Logos @relationship(type: "MUST_HAVE", direction: IN)
  mustHaveValidity: Validity @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveSoundness: Soundness @relationship(type: "MUST_HAVE", direction: OUT)
}

type Conclusion {
  word_count: Int!
  conclusion: [String!]
  logosMustHave: Logos @relationship(type: "MUST_HAVE", direction: IN)
  mustHaveValidity: Validity @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveSoundness: Soundness @relationship(type: "MUST_HAVE", direction: OUT)
}

type Validity {
  Validit_strength: Float!
  premiseMustHave: Premise @relationship(type: "MUST_HAVE", direction: IN)
  conclusionMustHave: Conclusion @relationship(type: "MUST_HAVE", direction: IN)
}

type Soundness {
  soundness_strength: Float!
  premiseMustHave: Premise @relationship(type: "MUST_HAVE", direction: IN)
  conclusionMustHave: Conclusion @relationship(type: "MUST_HAVE", direction: IN)
}

type Simple {
  subject: String!
  predicate: String!
  independebnt_clause: [String!]
  word_count: Int!
  sentenceMayBe: Sentence @relationship(type: "MAY_BE", direction: IN)
  mustHaveIndependentclause: IndependentClause @relationship(type: "MUST_HAVE", direction: OUT)
}

type Compound {
  clauses: [String!]
  amoun_of_indep_clauses: Int!
  conjunction_word: [String!]
  word_count: Int!
  sentenceMayBe: Sentence @relationship(type: "MAY_BE", direction: IN)
  mustHaveIndependentclause: IndependentClause @relationship(type: "MUST_HAVE", direction: OUT)
}

type CompoundComplex {
  clauses: [String!]
  amount_dep_clause: Int!
  amount_indep_clause: Int!
  word_count: Int!
  dep_clauses: [String!]
  indep_clauses: [String!]
  sentenceMayBe: Sentence @relationship(type: "MAY_BE", direction: IN)
  mustHaveDependentclause: DependentClause @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveIndependentclause: IndependentClause @relationship(type: "MUST_HAVE", direction: OUT)
}

type Declarative {
  punctuation: String!
  word_count: Int!
  sentenceIsType: Sentence @relationship(type: "IS_TYPE", direction: IN)
}

type Interrogative {
  punctuation: String!
  word_count: Int!
  subject: [String!]
  sentenceMayBe: Sentence @relationship(type: "MAY_BE", direction: IN)
  mayHavePunctuation: Punctuation @relationship(type: "MAY_HAVE", direction: OUT)
}

type Imperative {
  subject: String!
  conotation: String!
  word_count: Int!
  sentenceMayBe: Sentence @relationship(type: "MAY_BE", direction: IN)
  mustHavePartofspeech: PartOfSpeech @relationship(type: "MUST_HAVE", direction: OUT)
}

type Exclamatory {
  word_count: Int!
  punctuation: String!
  sentenceMayBe: Sentence @relationship(type: "MAY_BE", direction: IN)
  mayHavePunctuation: Punctuation @relationship(type: "MAY_HAVE", direction: OUT)
}

type Color {
  color_code: String!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type Weight {
  weight: Float!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type CharacterType {
  font: String!
  handwritten: String!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type CharacterStyle {
  italics: String!
  strikethrough: String!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type Alphabet {
  ASCII: String
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
}

type Numerics {
  number: String!
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
}

type SpecialCharacters {
  character: String!
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
}

type Listener {
  name: String!
  id: Int!
  agentsMayBe: Agents @relationship(type: "MAY_BE", direction: IN)
  mustHavePsychographics: Psychographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveDemographics: Demographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveMindstate: Mindstate @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveBias: Bias @relationship(type: "MUST_HAVE", direction: OUT)
  audienceOfText: Text @relationship(type: "AUDIENCE_OF", direction: OUT)
}

type DocumentOwner {
  name: String!
  id: Int!
  agentsMayBe: Agents @relationship(type: "MAY_BE", direction: IN)
  mustHavePsychographics: Psychographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveDemographics: Demographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveMindstate: Mindstate @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveBias: Bias @relationship(type: "MUST_HAVE", direction: OUT)
  ownsText: Text @relationship(type: "OWNS", direction: OUT)
}

type Knowledge {
  type: String!
  explanation: String!
  textMustHave: Text @relationship(type: "MUST_HAVE", direction: IN)
  mayBeProcedural: Procedural @relationship(type: "MAY_BE", direction: OUT)
  mayBeDeclarative: Declarative @relationship(type: "MAY_BE", direction: OUT)
  mayBeConditional: Conditional @relationship(type: "MAY_BE", direction: OUT)
}

type Procedural {
  purpose: String!
  knowledgeMayBe: Knowledge @relationship(type: "MAY_BE", direction: IN)
}

type Declarative {
  purpose: String!
  declaration: String!
  knowledgeMayBe: Knowledge @relationship(type: "MAY_BE", direction: IN)
}

type Conditional {
  purpose: String!
  premise: String!
  knowledgeMayBe: Knowledge @relationship(type: "MAY_BE", direction: IN)
}

type Topic {
  name: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type StyleScoreTensor {
  fig_lang: [String!]
  simile: [String!]
  metaphor: [String!]
  synecdoche: [String!]
  metonymy: [String!]
  personification: [String!]
  apostrophe: [String!]
  charactonym: [String!]
  syumbolism: [String!]
  allegory: [String!]
  imagery: [String!]
  styleContains: Style @relationship(type: "CONTAINS", direction: IN)
}