type Text {
  name: String!
  id: ID! @id @unique
  hasDocument: Document @relationship(type: "HAS", direction: OUT)
  propositionsDecision: Decision @relationship(type: "PROPOSITIONS", direction: OUT)
  mustHaveKnowledge: Knowledge @relationship(type: "MUST_HAVE", direction: OUT)
  referencesReference: Reference @relationship(type: "REFERENCES", direction: OUT)
  mustContainEnvironment: Environment @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainPurpose: Purpose @relationship(type: "MUST_CONTAIN", direction: OUT)
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  imageMayContain: Image @relationship(type: "MAY_CONTAIN", direction: IN)
  audiotranscriptMayContain: AudioTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
  imagetranscriptMayContain: ImageTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
  listenerAudienceOf: Listener @relationship(type: "AUDIENCE_OF", direction: IN)
  documentownerOwns: DocumentOwner @relationship(type: "OWNS", direction: IN)
}

type TextTranscript {
  name: String!
  id: ID! @id @unique
  mustContainText: Text @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainActor: Actor @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainTurn: Turn @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainTopic: Topic @relationship(type: "MUST_CONTAIN", direction: OUT)
  videotranscriptMayContain: VideoTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
}

type Actor {
  name: String!
  id: ID! @id @unique
  role: String!
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  spokeInTurn: Turn @relationship(type: "SPOKE_IN", direction: OUT)
  audiotranscriptMayContain: AudioTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
  imagetranscriptMayContain: ImageTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
}

type Turn {
  turn_number: Int!
  content: String!
  id: ID! @id @unique
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  actorSpokeIn: Actor @relationship(type: "SPOKE_IN", direction: IN)
  talkedAboutTopic: Topic @relationship(type: "TALKED_ABOUT", direction: OUT)
}

type Audio {
  file: String!
  size: Int!
  ifTranscribedAudiotranscript: AudioTranscript @relationship(type: "IF_TRANSCRIBED", direction: OUT)
  videoSegmentedBySound: Video @relationship(type: "SEGMENTED_BY_SOUND", direction: IN)
}

type Video {
  title: String!
  length: Int!
  link: String!
  frame_rate: Int!
  segmentedBySoundAudio: Audio @relationship(type: "SEGMENTED_BY_SOUND", direction: OUT)
  segmentedByImageFrame: Frame @relationship(type: "SEGMENTED_BY_IMAGE", direction: OUT)
  containsTranscriptVideotranscript: VideoTranscript @relationship(type: "CONTAINS_TRANSCRIPT", direction: OUT)
}

type Frame {
  Frame_number: Int!
  videoSegmentedByImage: Video @relationship(type: "SEGMENTED_BY_IMAGE", direction: IN)
  mustContainImage: Image @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Reference {
  title: String!
  author: String!
  source: String!
  type: String!
  textReferences: Text @relationship(type: "REFERENCES", direction: IN)
}

type Topic {
  name: String!
  id: ID! @id @unique
  texttranscriptMustContain: TextTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
  turnTalkedAbout: Turn @relationship(type: "TALKED_ABOUT", direction: IN)
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Image {
  coordinates: Int!
  pixels_x: Int!
  pixels: Int!
  pixels_y: Int!
  frameMustContain: Frame @relationship(type: "MUST_CONTAIN", direction: IN)
  mayContainText: Text @relationship(type: "MAY_CONTAIN", direction: OUT)
  ifTranscribedImagetranscript: ImageTranscript @relationship(type: "IF_TRANSCRIBED", direction: OUT)
}

type AudioTranscript {
  transcript: String!
  word_count: Int!
  sentence_count: Int!
  character_count: Int!
  audioIfTranscribed: Audio @relationship(type: "IF_TRANSCRIBED", direction: IN)
  mayContainText: Text @relationship(type: "MAY_CONTAIN", direction: OUT)
  mustContainTimestamp: Timestamp @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainVolume: Volume @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayContainActor: Actor @relationship(type: "MAY_CONTAIN", direction: OUT)
  videotranscriptMustContain: VideoTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Timestamp {
  time: String!
  audiotranscriptMustContain: AudioTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Volume {
  volume: Int!
  audiotranscriptMustContain: AudioTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type ImageTranscript {
  transcript: String!
  imageIfTranscribed: Image @relationship(type: "IF_TRANSCRIBED", direction: IN)
  mustContainColor: Color @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayContainEntity: Entity @relationship(type: "MAY_CONTAIN", direction: OUT)
  mayContainActor: Actor @relationship(type: "MAY_CONTAIN", direction: OUT)
  mayContainText: Text @relationship(type: "MAY_CONTAIN", direction: OUT)
  videotranscriptMustContain: VideoTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Color {
  color_code: String!
  imagetranscriptMustContain: ImageTranscript @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Entity {
  id: ID! @id @unique
  imagetranscriptMayContain: ImageTranscript @relationship(type: "MAY_CONTAIN", direction: IN)
}

type VideoTranscript {
  transcript: String!
  videoContainsTranscript: Video @relationship(type: "CONTAINS_TRANSCRIPT", direction: IN)
  mustContainImagetranscript: ImageTranscript @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainAudiotranscript: AudioTranscript @relationship(type: "MUST_CONTAIN", direction: OUT)
  mayContainTexttranscript: TextTranscript @relationship(type: "MAY_CONTAIN", direction: OUT)
}

type Document {
  turn_number: Int!
  speaker: String!
  content: String!
  role: String!
  id: ID! @id @unique
  textHas: Text @relationship(type: "HAS", direction: IN)
  hasEthosEthos: Ethos @relationship(type: "HAS_ETHOS", direction: OUT)
  hasPathosPathos: Pathos @relationship(type: "HAS_PATHOS", direction: OUT)
  hasLogosLogos: Logos @relationship(type: "HAS_LOGOS", direction: OUT)
  containsStyleStyle: Style @relationship(type: "CONTAINS_STYLE", direction: OUT)
  mustContainSoundstylistic: SoundStylistic @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainEuphony: Euphony @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainCohesion: Cohesion @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainHumor: Humor @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainClarity: Clarity @relationship(type: "MUST_CONTAIN", direction: OUT)
  containsSectionSection: Section @relationship(type: "CONTAINS_SECTION", direction: OUT)
  containsRhetoricalweight: RhetoricalWeight  @relationship(type: "CONTAINS", direction: OUT)
  mustContainTopic: Topic @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Paragraph {
  paragraph_number: Int!
  claims: [String!]
  sentence_sum: Int!
  claim_count: Int!
  hasSentenceSentence: Sentence @relationship(type: "HAS_SENTENCE", direction: OUT)
  mustContainCharacter: Character @relationship(type: "MUST_CONTAIN", direction: OUT)
  sectionContainsParagraph: Section @relationship(type: "CONTAINS_PARAGRAPH", direction: IN)
}

type Sentence {
  setence: String!
  number_of_clauses: Int!
  word_sum: Int!
  sentence_index: Int!
  amount_dep_clause: Int!
  amount_indep_clause: Int!
  paragraphHasSentence: Paragraph @relationship(type: "HAS_SENTENCE", direction: IN)
  hasClauseIndependentclause: IndependentClause @relationship(type: "HAS_CLAUSE", direction: OUT)
  hasClauseDependentclause: DependentClause @relationship(type: "HAS_CLAUSE", direction: OUT)
  structureIsSimple: Simple @relationship(type: "STRUCTURE_IS", direction: OUT)
  structureIsCompound: Compound @relationship(type: "STRUCTURE_IS", direction: OUT)
  structureIsCompoundcomplex: CompoundComplex @relationship(type: "STRUCTURE_IS", direction: OUT)
  typeIsDeclarative: Declarative @relationship(type: "TYPE_IS", direction: OUT)
  typeIsInterrogative: Interrogative @relationship(type: "TYPE_IS", direction: OUT)
  typeIsImperative: Imperative @relationship(type: "TYPE_IS", direction: OUT)
  typeIsExclamatory: Exclamatory @relationship(type: "TYPE_IS", direction: OUT)
}

type IndependentClause {
  clause: String!
  word_count: Int!
  clause_index: Int!
  sentenceHasClause: Sentence @relationship(type: "HAS_CLAUSE", direction: IN)
  hasWordWord: Word @relationship(type: "HAS_WORD", direction: OUT)
  mayBeClaim: Claim @relationship(type: "MAY_BE", direction: OUT)
  mayBeMetaphor: Metaphor @relationship(type: "MAY_BE", direction: OUT)
  mayBeSimile: Simile @relationship(type: "MAY_BE", direction: OUT)
  mayBeFallacies: Fallacies @relationship(type: "MAY_BE", direction: OUT)
  simpleMustHave: Simple @relationship(type: "MUST_HAVE", direction: IN)
  compoundMustHave: Compound @relationship(type: "MUST_HAVE", direction: IN)
  compoundcomplexMustHave: CompoundComplex @relationship(type: "MUST_HAVE", direction: IN)
}

type Word {
  word_length: Int!
  character_sum: Int!
  Word_index: Int!
  independentclauseHasWord: IndependentClause @relationship(type: "HAS_WORD", direction: IN)
  mustContainCharacter: Character @relationship(type: "MUST_CONTAIN", direction: OUT)
  isPartofspeech: PartOfSpeech @relationship(type: "IS", direction: OUT)
  mayBeNamedentity: NamedEntity @relationship(type: "MAY_BE", direction: OUT)
  dependentclauseHasWord: DependentClause @relationship(type: "HAS_WORD", direction: IN)
}

type Character {
  character_index: Int!
  character: String!
  paragraphMustContain: Paragraph @relationship(type: "MUST_CONTAIN", direction: IN)
  wordMustContain: Word @relationship(type: "MUST_CONTAIN", direction: IN)
  mayBePunctuation: Punctuation @relationship(type: "MAY_BE", direction: OUT)
  mustHaveColor: Color @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveWeight: Weight @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveCharactertype: CharacterType @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveCharacterstyle: CharacterStyle @relationship(type: "MUST_HAVE", direction: OUT)
  mayBeAlphabet: Alphabet @relationship(type: "MAY_BE", direction: OUT)
  mayBeNumerics: Numerics @relationship(type: "MAY_BE", direction: OUT)
  mayBeSpecialcharacters: SpecialCharacters @relationship(type: "MAY_BE", direction: OUT)
}

type Punctuation {
  mark: String!
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
  interrogativeMayHave: Interrogative @relationship(type: "MAY_HAVE", direction: IN)
  exclamatoryMayHave: Exclamatory @relationship(type: "MAY_HAVE", direction: IN)
}

type Claim {
  Claim: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type Metaphor {
  Metaphor: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type Simile {
  Simile: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type DependentClause {
  clause: String!
  word_count: Int!
  clause_index: Int!
  sentenceHasClause: Sentence @relationship(type: "HAS_CLAUSE", direction: IN)
  hasWordWord: Word @relationship(type: "HAS_WORD", direction: OUT)
  mustContainArgument: Argument @relationship(type: "MUST_CONTAIN", direction: OUT)
  compoundcomplexMustHave: CompoundComplex @relationship(type: "MUST_HAVE", direction: IN)
}

type PartOfSpeech {
  word_count: Int!
  wordIs: Word @relationship(type: "IS", direction: IN)
  imperativeMustHave: Imperative @relationship(type: "MUST_HAVE", direction: IN)
}

type NamedEntity {
  id: ID! @id @unique
  name: String!
  wordMayBe: Word @relationship(type: "MAY_BE", direction: IN)
  externalactorsMayContain: ExternalActors @relationship(type: "MAY_CONTAIN", direction: IN)
}

type Argument {
  Argument: [String!]
  word_count: Int!
  premises: [String!]
  conclustion: [String!]
  consequences: [String!]
  premise_count: Int!
  dependentclauseMustContain: DependentClause @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainPremise: Premise @relationship(type: "MUST_CONTAIN", direction: OUT)
  mustContainConsequence: Consequence @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Ethos {
  score: [Float!]
  explanation: String!
  documentHasEthos: Document @relationship(type: "HAS_ETHOS", direction: IN)
  contributesToAppeal: Appeal @relationship(type: "CONTRIBUTES_TO", direction: OUT)
  credibilityAppealsTo: Credibility  @relationship(type: "APPEALS_TO", direction: IN)
  authorityAppealsTo: Authority @relationship(type: "APPEALS_TO", direction: IN)
  reliabilityAppealsTo: Reliability @relationship(type: "APPEALS_TO", direction: IN)
  powerAppealsTo: Power @relationship(type: "APPEALS_TO", direction: IN)
  trustAppealsTo: Trust @relationship(type: "APPEALS_TO", direction: IN)
}

type Pathos {
  score: [Float!]
  explanation: String!
  documentHasPathos: Document @relationship(type: "HAS_PATHOS", direction: IN)
  contributesToAppeal: Appeal @relationship(type: "CONTRIBUTES_TO", direction: OUT)
  joyAppealsTo: Joy @relationship(type: "APPEALS_TO", direction: IN)
  sadnessAppealsTo: Sadness @relationship(type: "APPEALS_TO", direction: IN)
  anticipationAppealsTo: Anticipation @relationship(type: "APPEALS_TO", direction: IN)
  surpriseAppealsTo: Surprise @relationship(type: "APPEALS_TO", direction: IN)
  trustAppealsTo: Trust @relationship(type: "APPEALS_TO", direction: IN)
  disgustAppealsTo: Disgust @relationship(type: "APPEALS_TO", direction: IN)
  rageAppealsTo: Rage @relationship(type: "APPEALS_TO", direction: IN)
  fearAppealsTo: Fear @relationship(type: "APPEALS_TO", direction: IN)
}

type Logos {
  score: [Float!]
  explanation: String!
  documentHasLogos: Document @relationship(type: "HAS_LOGOS", direction: IN)
  mustHavePremise: Premise @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveConclusion: Conclusion @relationship(type: "MUST_HAVE", direction: OUT)
  contributesToAppeal: Appeal @relationship(type: "CONTRIBUTES_TO", direction: OUT)
  premisestrengthInfluences: PremiseStrength @relationship(type: "INFLUENCES", direction: IN)
  consequencestrengthInfluences: ConsequenceStrength @relationship(type: "INFLUENCES", direction: IN)
  validitystrengthInfluences: ValidityStrength @relationship(type: "INFLUENCES", direction: IN)
  soundnessstrengthInfluences: SoundnessStrength  @relationship(type: "INFLUENCES", direction: IN)
}

type Style {
  style_score_tensor: [Int!]
  register: Int!
  sound_stylistic: Int!
  euphony_hueristic: Int!
  documentContainsStyle: Document @relationship(type: "CONTAINS_STYLE", direction: IN)
  containsStylescoretensor: StyleScoreTensor @relationship(type: "CONTAINS", direction: OUT)
}

type SoundStylistic {
  rhyme_score: Float!
  alliteration_score: Float!
  assonance_score: Float!
  consonance_score: Float!
  rhythm_score: Float!
  onomatopoeia: [String!]
  rhyme_explanation: String!
  alliteration_explanation: String!
  assonance_explanation: String!
  consonance_explanation: String!
  rythm_explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Euphony {
  three_syllable_words: [String!]
  three_syllable_count: Int!
  short_vowels_words: [String!]
  stress_pattern_words: [String!]
  short_vowels_count: Int!
  stress_pattern_count: Int!
  count: Int!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Cohesion {
  Relevancy_Score: Float!
  Continuity_Score: Float!
  topic_transition_Score: Float!
  Relevancy_explanation: String!
  continuity_explanation: String!
  topic_transition_explanation: String!
  score: Float!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Humor {
  score: Float!
  explanation: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Clarity {
  score: Float!
  grammar_expl: String!
  readability_score: Float!
  grammar_score: Float!
  readability_expl: String!
  documentMustContain: Document @relationship(type: "MUST_CONTAIN", direction: IN)
  persuasivecoefficientProductOf: PersuasiveCoefficient @relationship(type: "PRODUCT_OF", direction: IN)
  readabilityContributesTo: Readability @relationship(type: "CONTRIBUTES_TO", direction: IN)
  grammarContributesTo: Grammar @relationship(type: "CONTRIBUTES_TO", direction: IN)
}

type Agents {
  name: String!
  mayBeListener: Listener @relationship(type: "MAY_BE", direction: OUT)
  mayBeDocumentowner: DocumentOwner @relationship(type: "MAY_BE", direction: OUT)
}

type ExternalActors {
  name: String!
  id: ID! @id @unique
  mayContainNamedentity: NamedEntity @relationship(type: "MAY_CONTAIN", direction: OUT)
  mustHavePsychographics: Psychographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveDemographics: Demographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveMindstate: Mindstate @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveBias: Bias @relationship(type: "MUST_HAVE", direction: OUT)
}

type Fallacies {
  fallacy_type: String!
  independentclauseMayBe: IndependentClause @relationship(type: "MAY_BE", direction: IN)
}

type Premise {
  parameters: [String!]
  index: Int!
  word_count: Int!
  argumentMustContain: Argument @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainPremiseparameters: PremiseParameters @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type Consequence {
  parameters: [String!]
  index: Int!
  word_count: Int!
  argumentMustContain: Argument @relationship(type: "MUST_CONTAIN", direction: IN)
  mustContainConsequenceparameters: ConsequenceParameters @relationship(type: "MUST_CONTAIN", direction: OUT)
}

type PremiseParameters {
  accuracy: Float!
  premiseMustContain: Premise @relationship(type: "MUST_CONTAIN", direction: IN)
}

type ConsequenceParameters {
  plausibility: Float!
  consequenceMustContain: Consequence @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Section {
  section_name: String!
  section_number: Int!
  documentContainsSection: Document @relationship(type: "CONTAINS_SECTION", direction: IN)
  containsParagraphParagraph: Paragraph @relationship(type: "CONTAINS_PARAGRAPH", direction: OUT)
}

type Environment {
  context: String!
  audience: String!
  purpose: String!
  language: String!
  textMustContain: Text @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Purpose {
  purpose: String!
  audience: String!
  textMustContain: Text @relationship(type: "MUST_CONTAIN", direction: IN)
}

type Psychographics {
  personality: String!
  interests: [String!]
  beliefs: [String!]
  vector: [Int!]
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
  personatensorBas: PersonaTensor @relationship(type: "BAS", direction: IN)
}

type Demographics {
  age: Int!
  gender: String!
  race: String!
  ethnicity: String!
  income: Int!
  location: String!
  vector: [Int!]
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
  personatensorBasedOn: PersonaTensor @relationship(type: "BASED_ON", direction: IN)
}

type Mindstate {
  emotional_state: String!
  cognitive_state: String!
  confidence: String!
  vector: [Int!]
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
  personatensorBasedOn: PersonaTensor @relationship(type: "BASED_ON", direction: IN)
}

type Bias {
  bias_type: String!
  category: String!
  cognitive_influence: [String!]
  emotional_influence: [String!]
  externalactorsMustHave: ExternalActors @relationship(type: "MUST_HAVE", direction: IN)
  listenerMustHave: Listener @relationship(type: "MUST_HAVE", direction: IN)
  documentownerMustHave: DocumentOwner @relationship(type: "MUST_HAVE", direction: IN)
}

type Decision {
  decision: String!
  textPropositions: Text @relationship(type: "PROPOSITIONS", direction: IN)
}

type Premise {
  premise_strength: Float!
  logosMustHave: Logos @relationship(type: "MUST_HAVE", direction: IN)
  mustHaveValidity: Validity @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveSoundness: Soundness @relationship(type: "MUST_HAVE", direction: OUT)
}

type Conclusion {
  word_count: Int!
  conclusion: [String!]
  logosMustHave: Logos @relationship(type: "MUST_HAVE", direction: IN)
  mustHaveValidity: Validity @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveSoundness: Soundness @relationship(type: "MUST_HAVE", direction: OUT)
}

type Validity {
  validity_strength: Float!
  premiseMustHave: Premise @relationship(type: "MUST_HAVE", direction: IN)
  conclusionMustHave: Conclusion @relationship(type: "MUST_HAVE", direction: IN)
}

type Soundness {
  soundness_strength: Float!
  premiseMustHave: Premise @relationship(type: "MUST_HAVE", direction: IN)
  conclusionMustHave: Conclusion @relationship(type: "MUST_HAVE", direction: IN)
}

type Simple {
  subject: String!
  predicate: String!
  independebnt_clause: [String!]
  word_count: Int!
  sentenceStructureIs: Sentence @relationship(type: "STRUCTURE_IS", direction: IN)
  mustHaveIndependentclause: IndependentClause @relationship(type: "MUST_HAVE", direction: OUT)
}

type Compound {
  clauses: [String!]
  amoun_of_indep_clauses: Int!
  conjunction_word: [String!]
  word_count: Int!
  sentenceStructureIs: Sentence @relationship(type: "STRUCTURE_IS", direction: IN)
  mustHaveIndependentclause: IndependentClause @relationship(type: "MUST_HAVE", direction: OUT)
}

type CompoundComplex {
  clauses: [String!]
  amount_dep_clause: Int!
  amount_indep_clause: Int!
  word_count: Int!
  dep_clauses: [String!]
  indep_clauses: [String!]
  sentenceStructureIs: Sentence @relationship(type: "STRUCTURE_IS", direction: IN)
  mustHaveDependentclause: DependentClause @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveIndependentclause: IndependentClause @relationship(type: "MUST_HAVE", direction: OUT)
}

type Declarative {
  punctuation: String!
  word_count: Int!
  sentenceTypeIs: Sentence @relationship(type: "TYPE_IS", direction: IN)
}

type Interrogative {
  punctuation: String!
  word_count: Int!
  subject: [String!]
  sentenceTypeIs: Sentence @relationship(type: "TYPE_IS", direction: IN)
  mayHavePunctuation: Punctuation @relationship(type: "MAY_HAVE", direction: OUT)
}

type Imperative {
  subject: String!
  conotation: String!
  word_count: Int!
  sentenceTypeIs: Sentence @relationship(type: "TYPE_IS", direction: IN)
  mustHavePartofspeech: PartOfSpeech @relationship(type: "MUST_HAVE", direction: OUT)
}

type Exclamatory {
  word_count: Int!
  punctuation: String!
  sentenceTypeIs: Sentence @relationship(type: "TYPE_IS", direction: IN)
  mayHavePunctuation: Punctuation @relationship(type: "MAY_HAVE", direction: OUT)
}

type Color {
  color_code: String!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type Weight {
  weight: Float!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type CharacterType {
  font: String!
  handwritten: String!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type CharacterStyle {
  italics: String!
  strikethrough: String!
  characterMustHave: Character @relationship(type: "MUST_HAVE", direction: IN)
}

type Alphabet {
  ASCII: String
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
}

type Numerics {
  number: String!
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
}

type SpecialCharacters {
  character: String!
  characterMayBe: Character @relationship(type: "MAY_BE", direction: IN)
}

type Listener {
  name: String!
  id: ID! @id @unique
  agentsMayBe: Agents @relationship(type: "MAY_BE", direction: IN)
  mustHavePsychographics: Psychographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveDemographics: Demographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveMindstate: Mindstate @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveBias: Bias @relationship(type: "MUST_HAVE", direction: OUT)
  audienceOfText: Text @relationship(type: "AUDIENCE_OF", direction: OUT)
}

type DocumentOwner {
  name: String!
  id: ID! @id @unique
  agentsMayBe: Agents @relationship(type: "MAY_BE", direction: IN)
  mustHavePsychographics: Psychographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveDemographics: Demographics @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveMindstate: Mindstate @relationship(type: "MUST_HAVE", direction: OUT)
  mustHaveBias: Bias @relationship(type: "MUST_HAVE", direction: OUT)
  ownsText: Text @relationship(type: "OWNS", direction: OUT)
}

type Knowledge {
  type: String!
  explanation: String!
  textMustHave: Text @relationship(type: "MUST_HAVE", direction: IN)
  mayBeProcedural: Procedural @relationship(type: "MAY_BE", direction: OUT)
  mayBeDeclarative: Declarative @relationship(type: "MAY_BE", direction: OUT)
  mayBeConditional: Conditional @relationship(type: "MAY_BE", direction: OUT)
}

type Procedural {
  purpose: String!
  knowledgeMayBe: Knowledge @relationship(type: "MAY_BE", direction: IN)
}

type Declarative {
  purpose: String!
  declaration: String!
  knowledgeMayBe: Knowledge @relationship(type: "MAY_BE", direction: IN)
}

type Conditional {
  purpose: String!
  premise: String!
  knowledgeMayBe: Knowledge @relationship(type: "MAY_BE", direction: IN)
}

type StyleScoreTensor {
  fig_lang: [String!]
  simile: [String!]
  metaphor: [String!]
  synecdoche: [String!]
  metonymy: [String!]
  personification: [String!]
  apostrophe: [String!]
  charactonym: [String!]
  syumbolism: [String!]
  allegory: [String!]
  imagery: [String!]
  styleContains: Style @relationship(type: "CONTAINS", direction: IN)
}

type PersuasiveResonance {
  score: [Int!]
  valid_Probability: [Float!]
  invalid_Probability: [Float!]
  abstain_Probability: [Float!]
  x_Probability: [Float!]
  parameterOfPersuasiveforce: PersuasiveForce @relationship(type: "PARAMETER_OF", direction: OUT)
  parameterOfPersonatensor: PersonaTensor @relationship(type: "PARAMETER_OF", direction: OUT)
}

type PersuasiveForce {
  vector: [Int!]
  persuasiveresonanceParameterOf: PersuasiveResonance @relationship(type: "PARAMETER_OF", direction: IN)
  productOfRhetoricalweight: RhetoricalWeight  @relationship(type: "PRODUCT_OF", direction: OUT)
  productOfPersuasivecoefficient: PersuasiveCoefficient @relationship(type: "PRODUCT_OF", direction: OUT)
}

type PersonaTensor {
  tensor: [Int!]
  persuasiveresonanceParameterOf: PersuasiveResonance @relationship(type: "PARAMETER_OF", direction: IN)
  basedOnDemographics: Demographics @relationship(type: "BASED_ON", direction: OUT)
  basPsychographics: Psychographics @relationship(type: "BAS", direction: OUT)
  basedOnMindstate: Mindstate @relationship(type: "BASED_ON", direction: OUT)
}

type RhetoricalWeight  {
  weight: Int!
  rhetorical_weight: [Int!]!
  documentContains: Document @relationship(type: "CONTAINS", direction: IN)
  persuasiveforceProductOf: PersuasiveForce @relationship(type: "PRODUCT_OF", direction: IN)
  characterweightFactorsIn: CharacterWeight @relationship(type: "FACTORS_IN", direction: IN)
  wordweightFactorsIn: WordWeight @relationship(type: "FACTORS_IN", direction: IN)
  sentenceweightFactorsIn: SentenceWeight @relationship(type: "FACTORS_IN", direction: IN)
  namedentityweightFactorsIn: NamedEntityWeight @relationship(type: "FACTORS_IN", direction: IN)
}

type PersuasiveCoefficient {
  coefficient: Int!
  persuasiveforceProductOf: PersuasiveForce @relationship(type: "PRODUCT_OF", direction: IN)
  productOfAppeal: Appeal @relationship(type: "PRODUCT_OF", direction: OUT)
  productOfRelevancy: Relevancy @relationship(type: "PRODUCT_OF", direction: OUT)
  productOfDistortion: Distortion  @relationship(type: "PRODUCT_OF", direction: OUT)
  productOfClarity: Clarity @relationship(type: "PRODUCT_OF", direction: OUT)
}

type Appeal {
  score: Int!
  ethosContributesTo: Ethos @relationship(type: "CONTRIBUTES_TO", direction: IN)
  pathosContributesTo: Pathos @relationship(type: "CONTRIBUTES_TO", direction: IN)
  logosContributesTo: Logos @relationship(type: "CONTRIBUTES_TO", direction: IN)
  persuasivecoefficientProductOf: PersuasiveCoefficient @relationship(type: "PRODUCT_OF", direction: IN)
}

type Relevancy {
  score: Int!
  persuasivecoefficientProductOf: PersuasiveCoefficient @relationship(type: "PRODUCT_OF", direction: IN)
}

type Distortion  {
  score: Int!
  persuasivecoefficientProductOf: PersuasiveCoefficient @relationship(type: "PRODUCT_OF", direction: IN)
  biasesContributesTo: Biases @relationship(type: "CONTRIBUTES_TO", direction: IN)
  fallaciesContributesTo: Fallacies @relationship(type: "CONTRIBUTES_TO", direction: IN)
}

type Readability {
  readability_Score: Int!
  readability_expl: String!
  contributesToClarity: Clarity @relationship(type: "CONTRIBUTES_TO", direction: OUT)
}

type Grammar {
  Grammar_score: Int!
  Flaw_Count: Int!
  grammer_expl: String!
  contributesToClarity: Clarity @relationship(type: "CONTRIBUTES_TO", direction: OUT)
}

type Biases {
  score: Int!
  explanation: String!
  contributesToDistortion: Distortion  @relationship(type: "CONTRIBUTES_TO", direction: OUT)
}

type Fallacies {
  score: Int!
  explanation: String!
  contributesToDistortion: Distortion  @relationship(type: "CONTRIBUTES_TO", direction: OUT)
}

type CharacterWeight {
  amount: Int!
  factorsInRhetoricalweight: RhetoricalWeight  @relationship(type: "FACTORS_IN", direction: OUT)
}

type WordWeight {
  amount: Int!
  factorsInRhetoricalweight: RhetoricalWeight  @relationship(type: "FACTORS_IN", direction: OUT)
}

type SentenceWeight {
  amount: Int!
  factorsInRhetoricalweight: RhetoricalWeight  @relationship(type: "FACTORS_IN", direction: OUT)
}

type NamedEntityWeight {
  amount: Int!
  factorsInRhetoricalweight: RhetoricalWeight  @relationship(type: "FACTORS_IN", direction: OUT)
}

type Credibility  {
  score: Int!
  explanation: String!
  appealsToEthos: Ethos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Authority {
  score: Int!
  explanation: String!
  appealsToEthos: Ethos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Reliability {
  score: Int!
  explanation: String!
  appealsToEthos: Ethos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Power {
  score: Int!
  explanation: String!
  appealsToEthos: Ethos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Joy {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Sadness {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Anticipation {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Surprise {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Trust {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
  appealsToEthos: Ethos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Disgust {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Rage {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type Fear {
  score: Int!
  explanation: String!
  appealsToPathos: Pathos @relationship(type: "APPEALS_TO", direction: OUT)
}

type PremiseStrength {
  score: Int!
  explanation: String!
  influencesLogos: Logos @relationship(type: "INFLUENCES", direction: OUT)
}

type ConsequenceStrength {
  score: Int!
  explanation: String!
  influencesLogos: Logos @relationship(type: "INFLUENCES", direction: OUT)
}

type ValidityStrength {
  score: Int!
  explanation: String!
  influencesLogos: Logos @relationship(type: "INFLUENCES", direction: OUT)
}

type SoundnessStrength  {
  score: Int!
  explanation: String!
  influencesLogos: Logos @relationship(type: "INFLUENCES", direction: OUT)
}